HerShoppingList/Controllers/JsonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HerShoppingList.Models;

namespace HerShoppingList.Controllers
{
    public class JsonController : Controller
    {
        //
        // GET: /StoreList/
        public JsonResult GetUniqueStores()
        {
            var returnList = new List<string>();
            using (var conn = MyConfig.SqlConnection())
            {
                conn.Open();
                using (var cmd = new SqlCommand("GetUniqueStores", conn) { CommandType = CommandType.StoredProcedure })
                {
                    using (var reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {

                            returnList.Add(reader.GetString(0));
                        }
                    }
                }

            }
            return this.Json(returnList,JsonRequestBehavior.AllowGet);
        }
	}
}

HerShoppingList/Controllers/ReceiptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HerShoppingList.Models;

namespace HerShoppingList.Controllers
{
    public class ReceiptController : Controller
    {
        //
        // GET: /Receipt/
        private Receipt _receipt;
        public ActionResult Index()
        {
            if (_receipt == null)
                _receipt = new Receipt();
            Session.Add("Receipt",_receipt);
            return View(_receipt);
        }

        [HttpPost]
        public ActionResult AddItem(Receipt receipt)
        {
            
            receipt.Items.Add(receipt.NewItem);
            _receipt = receipt;
            if (ModelState.IsValid)
            {

                return View("Index", _receipt);
            }
            return View("Index", _receipt);
        }
        //
        // GET: /Receipt/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Receipt/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Receipt/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Receipt/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Receipt/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Receipt/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Receipt/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HerShoppingList/Views/Receipt/Index.cshtml
@using System.Activities.Statements
@using HerShoppingList.Models
@model HerShoppingList.Models.Receipt

@{
    ViewBag.Title = "Receipt Builder";
}

<script type="text/javascript">
    var stores = [];
    $(document).ready(function () {
        GetUniqueStores();
        $("#Name").val("@Model.Name");
        $("#EntryDate").val("@Model.EntryDate.Date.ToShortDateString()");
        $("#Store.Name").val("@Model.Store.Name");
        $("#txtRecTotal").val("@Model.ReceiptTotal");
        $("#EntryDate").datepicker();
        
    });
    var PushStores = function (data) {
        var tStores = [];
        for (var a in data) {
            tStores.push(data[a]);
        }
        return tStores;
    };
    var GetUniqueStores = function () {
        $.getJSON("@Url.Action("GetUniqueStores","Json")", function (data) {
            stores = PushStores(data);
            $("#Store.Name").autocomplete({ source: stores });
        });
    };
</script>

<form class="form-horizontal" method="POST" action="@Url.Action("AddItem","Receipt")">
    <div class="jumbotron">
        <div id="main" class="panel panel-primary">

            <div class="panel-heading"> <h1 class="panel-title">Receipt Builder</h1></div>
            <div class="panel-body">

                <fieldset>
                    @Html.LabelFor(model => model.Name)
                    @Html.EditorFor(model => model.Name)

                    @Html.LabelFor(model => model.Store.Name)
                    @Html.EditorFor(model => model.Store.Name)

                    @Html.LabelFor(model => model.EntryDate)
                    @Html.EditorFor(model => model.EntryDate)
                </fieldset>

            </div>


        </div>
    </div>

    <table class="table table-bordered table-condensed table-hover table-responsive table-striped">
        <thead>
            <tr>
                <td>
                    <label class="control-label">#</label>
                </td>
                <td>
                    <label class="control-label">Item</label>
                </td>
                <td>
                    <label class="control-label">Unit</label>
                </td>
                <td>
                    <label class="control-label">Quantity</label>
                </td>
                <td>
                    <label class="control-label">UnitPrice</label>
                </td>
                <td>
                    <label class="control-label">Category</label>
                </td>
                <td>
                    <label class="control-label">Total</label>
                </td>
            </tr>
            <tr>
               
                    <td>
                        <button class="btn-sm btn-danger" style="border-radius: 50%; background-color: red;" name="Submit" id="Submit" type="submit">+</button>
                    </td>
                    
                    <td>
                        @Html.EditorFor(model => model.NewItem.Name)
                    </td>
                    
                    <td>
                        @Html.EditorFor(model => model.NewItem.UnitType)
                    </td>
                    
                    <td>
                        @Html.EditorFor(model => model.NewItem.Quantity)
                    </td>
                    
                    <td>
                        @Html.EditorFor(model => model.NewItem.UnitPrice)
                    </td>
                    
                    <td>
                        @Html.EditorFor(model => model.NewItem.Category.Name)<br/>
                        @Html.EditorFor(model => model.NewItem.Category.IsTaxable)
                    </td>
                    
                    <td>
                        @Html.DisplayFor(m => m.ReceiptTotal)
                    </td>
                    
                
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Items.Count(); i++)
            {
                <tr>
                    <td>
                    @(i+1)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Items[i].Name)
                        @Html.HiddenFor(m => m.Items[i].Name)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Items[i].UnitType)
                        @Html.HiddenFor(m => m.Items[i].UnitType)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Items[i].Quantity)
                        @Html.HiddenFor(m => m.Items[i].Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Items[i].UnitPrice)
                        @Html.HiddenFor(m => m.Items[i].UnitPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Items[i].Category.Name)
                        @Html.HiddenFor(m => m.Items[i].Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Items[i].ItemPrice)
                    </td>
                </tr>
            }
        </tbody>

        <tfoot></tfoot>
    </table>
    @for (int i = 0; i < Model.Items.Count(); i++)
    {
        Html.HiddenFor(model => Model.Items.ToList()[i].Name);
        Html.HiddenFor(model => Model.Items.ToList()[i].UnitType);
        Html.HiddenFor(model => Model.Items.ToList()[i].Quantity);
        Html.HiddenFor(model => Model.Items.ToList()[i].UnitPrice);
        Html.HiddenFor(model => Model.Items.ToList()[i].Category.Name);
    }
</form>

HerShoppingList/Views/Receipt/Item.cshtml
@model HerShoppingList.Models.Item

<tr>
    <td>
        
    </td>
    <td>
        @Model.Name;
    </td>
    <td>
        @Model.UnitType
    </td>
    <td>
        @Model.Quantity
    </td>
    <td>
        @Model.UnitPrice
    </td>
    <td>
        @Model.Category.Name
    </td>
    <td>
        @Html.LabelFor(model => model.ItemPrice)
    </td>
</tr>

HerShoppingList/Views/Receipt/ItemEditor.cshtml
@model HerShoppingList.Models.Item


    <td>
    <button class="btn-sm btn-danger" style="border-radius: 50%; background-color: red;" name="Submit" id="Submit" type="submit">+</button>
</td>
    <td>
        @Html.EditorFor(model => model.Name)
    </td>
    <td>
        @Html.EditorFor(model => model.UnitType)
    </td>
    <td>
        @Html.EditorFor(model => model.Quantity)
    </td>
    <td>
        @Html.EditorFor(model => model.UnitPrice)
    </td>
    <td>
        @Html.EditorFor(model => model.Category.Name)
    </td>
    <td>
        @Html.EditorFor(model => model.ItemPrice)
    </td>

HerShoppingList/Views/Receipt/ItemList.cshtml
@model HerShoppingList.Models.Items

@if (Model != null)
{
    
    foreach (var item in Model)
    {
        @Html.Partial("Item",item)
    }
}

HerShoppingList/Views/Receipt/List.cshtml
@model IEnumerable<HerShoppingList.Models.Items>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>